# Generated by Django 3.1.1 on 2020-09-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200921_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='core.Category'),
        ),
    ]
