# Generated by Django 3.1.1 on 2020-09-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200921_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
