# Generated by Django 3.1.1 on 2020-09-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ans_upvoted',
            field=models.ManyToManyField(blank=True, null=True, to='core.answer'),
        ),
    ]
